version: "3.3"

services:
  mongo:
    image: mongo:3-stretch
    volumes:
    - db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: StorageService
      MONGO_INITDB_ROOT_PASSWORD: StorageService
      MONGO_INITDB_DATABASE: StorageService

  storage_service:
    image: uprefer/storageservice:v0.1.0
    ports:
    - 8080:80
    depends_on:
    - mongo
    environment:
      STORAGESERVICE_MONGO_IP: mongo
      STORAGESERVICE_MONGO_PORT: 27017
      STORAGESERVICE_MONGO_USER: StorageService
      STORAGESERVICE_MONGO_PASSWORD: StorageService
      STORAGESERVICE_MONGO_DB: StorageService
      STORAGESERVICE_PORT: 80
    links:
    - mongo:mongo

volumes:
  db: