// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/UPrefer/StorageService/model"

// IArtifactDao is an autogenerated mock type for the IArtifactDao type
type IArtifactDao struct {
	mock.Mock
}

// CreateArtifact provides a mock function with given fields: _a0
func (_m *IArtifactDao) CreateArtifact(_a0 *model.ArtifactDTO) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ArtifactDTO) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// DeleteWaitingForUploadArtifact provides a mock function with given fields: id
func (_m *IArtifactDao) DeleteWaitingForUploadArtifact(id string) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// FindUploadedArtifact provides a mock function with given fields: id
func (_m *IArtifactDao) FindUploadedArtifact(id string) (*model.ArtifactDTO, error) {
	ret := _m.Called(id)

	var r0 *model.ArtifactDTO
	if rf, ok := ret.Get(0).(func(string) *model.ArtifactDTO); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArtifactDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// FindWaitingForUploadArtifact provides a mock function with given fields: s
func (_m *IArtifactDao) FindWaitingForUploadArtifact(s string) (*model.ArtifactDTO, error) {
	ret := _m.Called(s)

	var r0 *model.ArtifactDTO
	if rf, ok := ret.Get(0).(func(string) *model.ArtifactDTO); ok {
		r0 = rf(s)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArtifactDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(s)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
