// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import model "github.com/UPrefer/StorageService/model"

// IArtifactService is an autogenerated mock type for the IArtifactService type
type IArtifactService struct {
	mock.Mock
}

// CreateArtifact provides a mock function with given fields: artifactDto
func (_m *IArtifactService) CreateArtifact(artifactDto *model.ArtifactDTO) (*model.ArtifactDTO, error) {
	ret := _m.Called(artifactDto)

	var r0 *model.ArtifactDTO
	if rf, ok := ret.Get(0).(func(*model.ArtifactDTO) *model.ArtifactDTO); ok {
		r0 = rf(artifactDto)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArtifactDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(*model.ArtifactDTO) error); ok {
		r1 = rf(artifactDto)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReadArtifact provides a mock function with given fields: id
func (_m *IArtifactService) ReadArtifact(id string) (*model.ArtifactDTO, error) {
	ret := _m.Called(id)

	var r0 *model.ArtifactDTO
	if rf, ok := ret.Get(0).(func(string) *model.ArtifactDTO); ok {
		r0 = rf(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ArtifactDTO)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
