// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// IBlobService is an autogenerated mock type for the IBlobService type
type IBlobService struct {
	mock.Mock
}

// SaveBlob provides a mock function with given fields: artifactID, contentType, reader
func (_m *IBlobService) SaveBlob(artifactID string, contentType string, reader io.ReadCloser) error {
	ret := _m.Called(artifactID, contentType, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, io.ReadCloser) error); ok {
		r0 = rf(artifactID, contentType, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
