// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"
import model "github.com/UPrefer/StorageService/model"

// IBlobDao is an autogenerated mock type for the IBlobDao type
type IBlobDao struct {
	mock.Mock
}

// SaveData provides a mock function with given fields: dto, contentType, reader
func (_m *IBlobDao) SaveData(dto *model.ArtifactDTO, contentType string, reader io.Reader) error {
	ret := _m.Called(dto, contentType, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(*model.ArtifactDTO, string, io.Reader) error); ok {
		r0 = rf(dto, contentType, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
