// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import io "io"
import mock "github.com/stretchr/testify/mock"

// IBlobService is an autogenerated mock type for the IBlobService type
type IBlobService struct {
	mock.Mock
}

// ReadBlob provides a mock function with given fields: artifactId
func (_m *IBlobService) ReadBlob(artifactId string) (string, string, int64, io.ReadCloser, error) {
	ret := _m.Called(artifactId)

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(artifactId)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 string
	if rf, ok := ret.Get(1).(func(string) string); ok {
		r1 = rf(artifactId)
	} else {
		r1 = ret.Get(1).(string)
	}

	var r2 int64
	if rf, ok := ret.Get(2).(func(string) int64); ok {
		r2 = rf(artifactId)
	} else {
		r2 = ret.Get(2).(int64)
	}

	var r3 io.ReadCloser
	if rf, ok := ret.Get(3).(func(string) io.ReadCloser); ok {
		r3 = rf(artifactId)
	} else {
		if ret.Get(3) != nil {
			r3 = ret.Get(3).(io.ReadCloser)
		}
	}

	var r4 error
	if rf, ok := ret.Get(4).(func(string) error); ok {
		r4 = rf(artifactId)
	} else {
		r4 = ret.Error(4)
	}

	return r0, r1, r2, r3, r4
}

// SaveBlob provides a mock function with given fields: artifactID, contentType, reader
func (_m *IBlobService) SaveBlob(artifactID string, contentType string, reader io.ReadCloser) error {
	ret := _m.Called(artifactID, contentType, reader)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, io.ReadCloser) error); ok {
		r0 = rf(artifactID, contentType, reader)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
